version: 2.1
jobs:
  build:
    docker:
    # ruby2.5.1を使用
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        - BUNDLER_VERSION: 2.0.2
        # - BUNDLER_VERSION: 1.17.3
        - RAILS_ENV: 'test'
    # mysql5.7を使用
    - image: circleci/mysql:5.7
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        # - MYSQL_ROOT_HOST: '127.0.0.1'
        - MYSQL_HOST: '127.0.0.1'

    # 自分のアプリディレクトリ名(実行ディレクトリ)を設定
    working_directory: ~/Collection

    # 実際の処理内容
    # CI環境上のworking_directoryにGitリポジトリをコピー
    steps:
    - checkout

    # キャッシュがsave_cacheされていればrestoreする
    - restore_cache:
        # restoreするキャッシュを複数指定
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.0.2
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    # packageなどのfileをcacheする
    - save_cache:
        # cacheするfileを設定
        paths:
        - ./vendor/bundle
        # cacheの名前を設定
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # databaseの設定
    - run:
        name: Databasesetup
        command: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

    # RSpecを走らせる記述
    - run:
        name: Run rspec
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"

          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $TEST_FILES

    # テストが終了したらstore_test_resultsを使用してテスト結果を保存する
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results
