default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME") { "root" } %>
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "localhost" } %>  

development:
  <<: *default
  database: originalApp_development
  host: localhost
  password:

test:
  <<: *default
  database: originalApp_test
  host: localhost
  password: 

production:
  <<: *default
  database: originalApp_production
  username: root
  password: <%= Rails.application.credentials.database_password %>